name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup CMake
        run: sudo apt-get install -y cmake g++

      - name: Build C++
        run: |
          cd cpp
          cmake -B build -S .
          cmake --build build
